# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gaodong/Documents/mobile/we-media

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gaodong/Documents/mobile/we-media

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gaodong/Documents/mobile/we-media/CMakeFiles /Users/gaodong/Documents/mobile/we-media/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gaodong/Documents/mobile/we-media/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libcef_dll_wrapper

# Build rule for target.
libcef_dll_wrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libcef_dll_wrapper
.PHONY : libcef_dll_wrapper

# fast build rule for target.
libcef_dll_wrapper/fast:
	$(MAKE) -f libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/build.make libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/build
.PHONY : libcef_dll_wrapper/fast

#=============================================================================
# Target rules for targets named cefclient

# Build rule for target.
cefclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cefclient
.PHONY : cefclient

# fast build rule for target.
cefclient/fast:
	$(MAKE) -f src/cefclient/CMakeFiles/cefclient.dir/build.make src/cefclient/CMakeFiles/cefclient.dir/build
.PHONY : cefclient/fast

#=============================================================================
# Target rules for targets named cefclient_Helper

# Build rule for target.
cefclient_Helper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cefclient_Helper
.PHONY : cefclient_Helper

# fast build rule for target.
cefclient_Helper/fast:
	$(MAKE) -f src/cefclient/CMakeFiles/cefclient_Helper.dir/build.make src/cefclient/CMakeFiles/cefclient_Helper.dir/build
.PHONY : cefclient_Helper/fast

#=============================================================================
# Target rules for targets named cefsimple

# Build rule for target.
cefsimple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cefsimple
.PHONY : cefsimple

# fast build rule for target.
cefsimple/fast:
	$(MAKE) -f src/cefsimple/CMakeFiles/cefsimple.dir/build.make src/cefsimple/CMakeFiles/cefsimple.dir/build
.PHONY : cefsimple/fast

#=============================================================================
# Target rules for targets named cefsimple_Helper

# Build rule for target.
cefsimple_Helper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cefsimple_Helper
.PHONY : cefsimple_Helper

# fast build rule for target.
cefsimple_Helper/fast:
	$(MAKE) -f src/cefsimple/CMakeFiles/cefsimple_Helper.dir/build.make src/cefsimple/CMakeFiles/cefsimple_Helper.dir/build
.PHONY : cefsimple_Helper/fast

#=============================================================================
# Target rules for targets named we-media

# Build rule for target.
we-media: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 we-media
.PHONY : we-media

# fast build rule for target.
we-media/fast:
	$(MAKE) -f src/core/CMakeFiles/we-media.dir/build.make src/core/CMakeFiles/we-media.dir/build
.PHONY : we-media/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... libcef_dll_wrapper"
	@echo "... cefclient"
	@echo "... cefclient_Helper"
	@echo "... cefsimple"
	@echo "... cefsimple_Helper"
	@echo "... we-media"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

